alumserv/AlumServ/config/routes.rb
AlumServ::Application.routes.draw do
  root to: 'pages#home'

  match '/about', to: 'pages#about'
  match '/contact', to: 'pages#contact'
  match '/signup', to: 'users#new'

  resources :schools

  resources :users
  match '/signup', to: 'users#new'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
end

alumserv/AlumServ/app/models/school.rb
class School < ActiveRecord::Base
  attr_accessible :address, :name
  has_and_belongs_to_many :user
end

alumserv/AlumServ/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :phone, :password
  has_and_belongs_to_many :schools

  validates :name, presence: true

  before_save { |user| user.email = email.downcase }
  before_save  :create_remember_token
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  validates :phone, presence: true, length: {is: 10}

  validates :password, presence: true, length: { minimum: 6 }

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

alumserv/AlumServ/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

alumserv/AlumServ/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

alumserv/AlumServ/app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schools }
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = School.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/new
  # GET /schools/new.json
  def new
    @school = School.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/1/edit
  def edit
    @school = School.find(params[:id])
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(params[:school])

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render json: @school, status: :created, location: @school }
      else
        format.html { render action: "new" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schools/1
  # PUT /schools/1.json
  def update
    @school = School.find(params[:id])

    respond_to do |format|
      if @school.update_attributes(params[:school])
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school = School.find(params[:id])
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end
end

alumserv/AlumServ/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in_user
      redirect_to user
    else
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

alumserv/AlumServ/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    if @user.save
    sign_in @user
    redirect_to @user
    else
      render 'new'
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

alumserv/AlumServ/app/helpers/application_helper.rb
module ApplicationHelper
# Returns the full title on a per-page basis.
def full_title(page_title)
    base_title = "AlumServ"
    if page_title.empty?
        base_title
    else
        "#{base_title} | #{page_title}"
    end
end
end

alumserv/AlumServ/app/helpers/pages_helper.rb
module PagesHelper
end

alumserv/AlumServ/app/helpers/schools_helper.rb
module SchoolsHelper
end

alumserv/AlumServ/app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

alumserv/AlumServ/app/helpers/users_helper.rb
module UsersHelper
end

alumserv/AlumServ/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
<div class="navbar-inner">
    <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
        <ul class="nav pull-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Sign in", '#' %></li>
            <li><%= link_to "Sign up", signup_path %></li>
            <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
                </ul>
            </li>
            <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
        </ul>
    </nav>
    </div>
</div>
</header>

alumserv/AlumServ/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

alumserv/AlumServ/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

</head>
<body>
    <%= render 'layouts/header' %>
    <header class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <%= link_to "ALUMSERV", root_path, id: "logo" %>
                <nav>
                    <ul class="nav pull-right">
                        <li><%= link_to "Home", root_path %></li>
                        <li><%= link_to "About", about_path %></li>
                        <li><%= link_to "Contact", contact_path %></li>
                        <li><%= link_to "Sign in", '#' %></li>
                        <li><%= link_to "Sign up", signup_path %></li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div class="container">
    <%= yield %>
    </div>
</body>
</html>

alumserv/AlumServ/app/views/pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>
About AlumServ here.
</p>

alumserv/AlumServ/app/views/pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
AlumServ contact here.
</p>

alumserv/AlumServ/app/views/pages/home.html.erb
<head>
  <meta charset="utf-8" />
  <% provide(:title, 'AlumServ') %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="description" content="AlumServ, connecting alumni with recent graduates.">
  <meta name="keywords" content="alumni, connect, graduates, recent, students, schools, networking">
</head>

<div class="center hero-unit">

<h1>ALUMSERV</h1>

<h2> Welcome to AlumServ</h2>
<p>something about alumserv</p>

<h2>Latest Updates</h2>
    <ul id="updatelist">
      <li>Johns Hopkins University connected to AlumServ.</li>
      <li>University of Maryland connected to AlumServ.</li>
    </ul>

<%= link_to image_tag("alumserv_logo.png", alt: "AlumServ"), '#' %>

alumserv/AlumServ/app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

alumserv/AlumServ/app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

alumserv/AlumServ/app/views/schools/index.html.erb
<h1>Listing schools</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schools.each do |school| %>
  <tr>
    <td><%= school.name %></td>
    <td><%= school.address %></td>
    <td><%= link_to 'Show', school %></td>
    <td><%= link_to 'Edit', edit_school_path(school) %></td>
    <td><%= link_to 'Destroy', school, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New School', new_school_path %>

alumserv/AlumServ/app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

alumserv/AlumServ/app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @school.name %>
</p>

<p>
  <b>Address:</b>
  <%= @school.address %>
</p>


<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>

alumserv/AlumServ/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

alumserv/AlumServ/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

alumserv/AlumServ/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.phone %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

alumserv/AlumServ/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>New User? Sign up here!</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

alumserv/AlumServ/app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h1><%= @user.name %></h1>

<p id="notice"><%= notice %></p>

<h2>
  <b>Email:</b>
  <%= @user.email %>
</h2>

<h2>
  <b>Phone:</b>
  <%= @user.phone %>
</h2>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>